import type { Metadata } from "next";
import { Saira_Stencil_One } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const Saira = Saira_Stencil_One({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Saira.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
